import TelegramBot from 'node-telegram-bot-api';
const token = process.env.TELEGRAM_BOT_TOKEN;
if (!token) throw new Error('TELEGRAM_BOT_TOKEN is required. Copy .env.example; never commit a token.');
const bot = new TelegramBot(token, { polling: true });
const configured = new Set((process.env.OPTED_IN_CHAT_IDS || '').split(',').map((v) => v.trim()).filter(Boolean));
const optedIn = new Set(configured);
const publicSite = process.env.PUBLIC_SITE_URL || 'https://tayanch.uz';
const telegramUrl = 'https://t.me/tayanch_go';
const courseMessage = `Narxlar va kurslar doim sayt sahifalarida tekshiriladi: ${publicSite}/narxlar/\n\nKurslar: ${publicSite}/kurslar/\n\nSavol bo‘lsa, ${telegramUrl} orqali yozing.`;
const paymentMessage = `To‘lovlar Telegram orqali qo‘lda tasdiqlanadi. Kurs nomini yuboring; amaldagi narx va rekvizitlar bevosita suhbatda tasdiqlanadi. Sayt yoki bot karta raqami, CVC yoki bank parolini so‘ramaydi.\n\nKurslar: ${publicSite}/kurslar/`;
bot.onText(/^\/start(?:\s|$)/, (msg) => { optedIn.add(String(msg.chat.id)); bot.sendMessage(msg.chat.id, 'Tayanch eslatmalariga ulandingiz. /stop bilan to‘xtatishingiz mumkin. Narxlar: /narxlar. To‘lov: /qanday_tolov.'); });
bot.onText(/^\/stop(?:\s|$)/, (msg) => { optedIn.delete(String(msg.chat.id)); bot.sendMessage(msg.chat.id, 'Eslatmalar to‘xtatildi.'); });
bot.onText(/^\/narxlar(?:\s|$)/, (msg) => bot.sendMessage(msg.chat.id, courseMessage));
bot.onText(/^\/qanday_tolov(?:\s|$)/, (msg) => bot.sendMessage(msg.chat.id, paymentMessage));
bot.on('message', (msg) => { if (typeof msg.text === 'string' && msg.text.startsWith('/') && !/^\/(start|stop|narxlar|qanday_tolov)(?:\s|$)/.test(msg.text)) bot.sendMessage(msg.chat.id, `Buyruqlar: /narxlar, /qanday_tolov, /stop. ${telegramUrl}`); });
const ms = 24 * 60 * 60 * 1000;
setInterval(async () => { for (const chatId of optedIn) { try { await bot.sendMessage(chatId, process.env.REMINDER_TEXT || 'Tayanch o‘qishingizni davom ettiring.'); } catch (error) { console.error('Reminder failed', chatId, error.message); } } }, ms);
console.log('Bot started. This process keeps opt-ins only in memory; use consented persistent storage for production.');
